# Stage 1: build
FROM node:20-alpine AS builder

WORKDIR /app

COPY docs/package*.json ./
RUN npm install

COPY docs/ ./
RUN CI=true npm run build


# Stage 2: serve
FROM caddy:2-alpine AS runtime

COPY --from=builder /app/build /srv

EXPOSE 8080

CMD ["caddy", "file-server", "--root", "/srv", "--listen", ":8080"]
